### ISSUE TITLE
Unable to import JSON config for redis connections

### ISSUE THREAD

**Issue by rcheng-roadie** [RedisInsight/RedisInsight#4571]
redisinsight-config.json works when manually inputted. `RI_PRE_SETUP_DATABASES_PATH` doesn't seem to be working on this version. I also have tried version 2.68 which doesn't even allowed manually inputing a JSON file.

Confirmed that the volume is mounted and the env variable exist in the pod. 
The only log is `Running docker-entry.sh`. This may suggest I need a different entry point to dynamically load in this json.

```
      volumes:
        - name: preload-config
          secret:
            secretName: redisinsight-config
      containers:
        - name: redisinsight
          image: "redis/redisinsight:2.42"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-ui
              containerPort: 5540
              protocol: TCP
          volumeMounts:
            - name: preload-config
              mountPath: /db/redisinsight-config.json
              subPath: redisinsight-config.json
          env:
            - name: RI_PRE_SETUP_DATABASES_PATH
              value: /db/redisinsight-config.json
```

Example redisinsight-config.json
```
[
      {
        "host": "master.asdf.usw2.cache.amazonaws.com",
        "port": 6379,
        "name": "some_api_3",
        "username": "",
        "password": "asdf_df",
        "database": 0,
        "ssl": true
      },
      {
        "host": "master.asdf.usw2.cache.amazonaws.com",
        "port": 6379,
        "name": "some_api",
        "username": "",
        "password": "asdf",
        "database": 1,
        "ssl": true
      },
      {
        "host": "master.asdf.usw2.cache.amazonaws.com",
        "port": 6379,
        "name": "some_api_2",
        "username": "",
        "password": "asf",
        "database": 0,
        "ssl": true
      }
]

```

**Comment by ArtemHoruzhenko** [comment]
Hi @rcheng-roadie, thank you for reporting this
1. At first I recommend to add unique "id" field to each database , e.g. `"id": "some_api_3"` and so on...
2. Regarding json file: seems like it is there but I'm not sure if Redis Insight can read it. Did you check access to the file?
3. If you want to enable stdout logs you can do it via these envs: 
   i. `RI_STDOUT_LOGGER=true`
   ii. and add more details there `RI_LOG_LEVEL=debug` this might help to find what exactly happened during database discovery from the file

**Comment by rcheng-roadie** [comment]
Thanks for the reply @ArtemHoruzhenko 

1. Added `id` field alongside with `name`
2. The file is available to read for root in the redis container
```
/db $ ls -la
total 12
drwxr-xr-x    2 root     root            38 May 23 14:57 .
drwxr-xr-x    1 root     root            62 May 23 14:57 ..
-rw-r--r--    1 root     root          9943 May 23 14:57 redisinsight-config.json
````
3. Thanks this helped a bit. Am seeing this module trying to retrieve the databases list. 
`[NestWinston] Info	5/23/2025, 2:58:03 PM [DatabaseService] Getting databases list - {"stack":[]}`


- Just to confirm, this method with ` RI_PRE_SETUP_DATABASES_PATH` is still supported in RedisInsights 2.x?

**Comment by ArtemHoruzhenko** [comment]
@rcheng-roadie Thank you for info
I think we've found an issue. Will work on fix

**Comment by ViktarStarastsenka** [comment]
@rcheng-roadie , this issue should be fixed with 2.70 (released today).

**Comment by rcheng-roadie** [comment]
@ArtemHoruzhenko @ViktarStarastsenka 

Hey guys, thanks for the update. I'm able to load the JSON config. 
However with the same settings as above, I'm still facing a couple issues:

- "ssl" configuration is not loaded in. 
- After selecting a Database and applying TLS, I am still unable to connect. Error message
```
Redis Insight] 1 5/28/2025, 3:57:54 PM   ERROR [TimeoutInterceptor] Request Timeout. GET /api/databases/roadie-tracking-perf/info - { stack: [ null ], data: [ null ] }
[Redis Insight] 1 5/28/2025, 3:57:54 PM   DEBUG [DatabaseInfoService] Getting database info for: roadie-tracking-perf - {
  clientMetadata: { databaseId: 'roadie-tracking-perf', context: 'Common' },
  sessionMetadata: {
    data: { data: {} },
    userId: '1',
    sessionId: '1',
    correlationId: 'ba196def-55a9-47f2-96a3-e8043f6f0d4b'
  }
}
```

The following above does not happen when the same configuration is loaded in manually. The following passwords are loading via ExternalSecrets Templating.
```
[
            {
              "host": "master.asdf.usw2.cache.amazonaws.com",
              "port": 6379,
              "id": "map-search",
              "name": "map-search",
              "username": "",
              "password": "{{ .MapSearchServer_REDIS_PW }}",
              "db": 0,
              "ssl": true
            },
            {
              "host": "master.asdf.usw2.cache.amazonaws.com",
              "port": 6379,
              "id": "sender-api",
              "name": "sender-api",
              "username": "",
              "password": "{{ .SenderApi_REDIS_PW }}",
              "db": 5,
              "ssl": true
            }
]
```

**Comment by rcheng-roadie** [comment]
@ArtemHoruzhenko Thank you for the amazing quick reply and solutions. It works!
